notifications:
  commits:      commits@flume.apache.org
  issues:       issues@flume.apache.org
  pullrequests: dev@flume.apache.org
  jira_options: link label comment 

staging:
  profile: ~
  whoami: asf-staging
  subdir: content

publish:
  profile: ~
  whoami: asf-site
  subdir: content
