notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label worklog

staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/flume

publish:
  profile: ~
  whoami: main-site-pro-out
  subdir: content/flume
