notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label worklog

staging:
  hostname: flume.apache.org
  profile: ~
  whoami: main-site-stg-out

publish:
  hostname: flume.apache.org
  profile: ~
  whoami: main-site-pro-out

# Dummy change to generate small Github event:
# 
# Thu Oct 10 20:18:29 CEST 2024
