notifications:
  commits:      commits@flume.apache.org
  issues:       issues@flume.apache.org
  pullrequests: dev@flume.apache.org
  jira_options: link label comment 

staging:
  hostname: flume.apache.org
  profile: ~
  whoami: asf-staging

publish:
  hostname: flume.apache.org
  profile: ~
  whoami: asf-site
